name: Makefile CI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: sudo apt install -y ninja-build&& ./configure --prefix=/usr --target-list=loongarch64-softmmu
      
    - name: make
      run:  make -j3
    - name: tar artifacts
      run: zip -r qemu-loongarch64.zip ./
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qemu-loongarch64
        path: qemu-loongarch64.zip

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 0.1.0
        files: "qemu-loongarch64.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
