name: Makefile CI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: sudo apt install -y ninja-build&& ./configure --prefix=/usr --target-list=loongarch64-softmmu
      
    - name: Install dependencies
      run:  make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
